name: CI/CD Pipeline Java -> Docker -> Minikube

on:
  push:
    branches: [ "main" ]  # Se déclenche sur push vers 'main'
  pull_request:           # Optionnel : pour les tests sur PR
    branches: [ "main" ]

env:
  APP_NAME: "mon-app-java"
  DOCKER_IMAGE: "tonuserdocker/${{ env.APP_NAME }}:${{ github.sha }}"

jobs:
  build-and-push:
    name: Build Docker Image & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .
          docker push ${{ env.DOCKER_IMAGE }}
